package ClassDiagramDSLMilosProrocic.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import java.util.Deque;
import jetbrains.mps.internal.collections.runtime.LinkedListSequence;
import java.util.LinkedList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_valid_Atribut_type_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_valid_Atribut_type_NonTypesystemRule() {
  }
  public void applyRule(final SNode a, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    Deque<String> allowedValues = LinkedListSequence.fromListAndArray(new LinkedList<String>(), "boolean", "integer", "string", "real", "undefined", "date", "datetime");

    SNode nodeDijagram = (SNode) SNodeOperations.getParent(SNodeOperations.getParent(a));

    for (SNode interfejs : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.interfejsi$5e0d))) {
      LinkedListSequence.fromLinkedListNew(allowedValues).addElement(SPropertyOperations.getString(interfejs, PROPS.name$MnvL));
    }

    for (SNode klasa : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.klase$5dLc))) {
      LinkedListSequence.fromLinkedListNew(allowedValues).addElement(SPropertyOperations.getString(klasa, PROPS.name$MnvL));
    }

    for (SNode enumeracija : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.enumeracije$oHuo))) {
      LinkedListSequence.fromLinkedListNew(allowedValues).addElement(SPropertyOperations.getString(enumeracija, PROPS.name$MnvL));
    }

    if (!(LinkedListSequence.fromLinkedListNew(allowedValues).contains(SPropertyOperations.getString(a, PROPS.tipAtributa$Len0)))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(a, "Tip " + SPropertyOperations.getString(a, PROPS.tipAtributa$Len0) + " nije validan. Odaberi neki od ugradjenih tipova ili postojecih objekata!", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "2465447832826093256", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Atribut$yg;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty tipAtributa$Len0 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565f7d1L, 0x3baa75e0c95b2eb1L, "tipAtributa");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink interfejsi$5e0d = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e999L, "interfejsi");
    /*package*/ static final SContainmentLink klase$5dLc = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e998L, "klase");
    /*package*/ static final SContainmentLink enumeracije$oHuo = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5490ab52L, "enumeracije");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Atribut$yg = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565f7d1L, "ClassDiagramDSLMilosProrocic.structure.Atribut");
  }
}
