package ClassDiagramDSLMilosProrocic.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_exists_in_Dijagram_Klasa_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_exists_in_Dijagram_Klasa_NonTypesystemRule() {
  }
  public void applyRule(final SNode v, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode nodeDijagram = (SNode) SNodeOperations.getParent(v);
    boolean klasaLevoPostoji = false;
    boolean klasaDesnoPostoji = false;

    for (SNode klasa : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.klase$5dLc))) {
      if (SPropertyOperations.getString(v, PROPS.nazivKlaseLevo$SDoj).equals(SPropertyOperations.getString(klasa, PROPS.name$MnvL))) {
        klasaLevoPostoji = true;
      }
      if (SPropertyOperations.getString(v, PROPS.nazivKlaseDesno$SDBk).equals(SPropertyOperations.getString(klasa, PROPS.name$MnvL))) {
        klasaDesnoPostoji = true;
      }
    }

    if (!(klasaLevoPostoji)) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(v, "Klasa " + SPropertyOperations.getString(v, PROPS.nazivKlaseLevo$SDoj) + " ne postoji", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "311480510048037401", null, errorTarget);
      }
    }

    if (!(klasaDesnoPostoji)) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(v, "Klasa " + SPropertyOperations.getString(v, PROPS.nazivKlaseDesno$SDBk) + " ne postoji", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "311480510048053578", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Veza$F6;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty nazivKlaseLevo$SDoj = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf549581ecL, "nazivKlaseLevo");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty nazivKlaseDesno$SDBk = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf549581edL, "nazivKlaseDesno");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink klase$5dLc = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e998L, "klase");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Veza$F6 = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, "ClassDiagramDSLMilosProrocic.structure.Veza");
  }
}
