package ClassDiagramDSLMilosProrocic.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_Kardinalnost_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_Kardinalnost_NonTypesystemRule() {
  }
  public void applyRule(final SNode k, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    try {
      if (SPropertyOperations.getInteger(k, PROPS.donjaVrednost$nL93) > Integer.parseInt(SPropertyOperations.getString(k, PROPS.gornjaVrednost$nLo4))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(k, "Donja vrednost mora biti manja od gornje!", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "4299378402590110282", null, errorTarget);
        }
      }
    } catch (Exception ex) {
      if (SPropertyOperations.getString(k, PROPS.gornjaVrednost$nLo4).charAt(0) != '*' || SPropertyOperations.getString(k, PROPS.gornjaVrednost$nLo4).length() != 1) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(k, "Karakter " + SPropertyOperations.getString(k, PROPS.gornjaVrednost$nLo4) + " nije validna kardinalnost", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "4299378402590130495", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Kardinalnost$DX;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty gornjaVrednost$nLo4 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f605L, "gornjaVrednost");
    /*package*/ static final SProperty donjaVrednost$nL93 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f604L, "donjaVrednost");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Kardinalnost$DX = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, "ClassDiagramDSLMilosProrocic.structure.Kardinalnost");
  }
}
