package ClassDiagramDSLMilosProrocic.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_valid_Kardinalnost_Veza_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_valid_Kardinalnost_Veza_NonTypesystemRule() {
  }
  public void applyRule(final SNode v, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SPropertyOperations.getEnum(v, PROPS.TipVeze$Sa5H) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e43eL, "ClassDiagramDSLMilosProrocic.structure.TipVezeEnum"), 0x505e9faf5487e447L, "kompozicija") && ((SPropertyOperations.getInteger(SLinkOperations.getTarget(v, LINKS.kardinalnostLevo$UmOH), PROPS.donjaVrednost$nL93) > 1 || SPropertyOperations.getInteger(SLinkOperations.getTarget(v, LINKS.kardinalnostLevo$UmOH), PROPS.donjaVrednost$nL93) < 0) || (!(SPropertyOperations.getString(SLinkOperations.getTarget(v, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4).equals("*")) && Integer.parseInt(SPropertyOperations.getString(SLinkOperations.getTarget(v, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4)) > 1) || (SPropertyOperations.getString(SLinkOperations.getTarget(v, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4).equals("*")))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(v, "Kardinalnost sa leve strane kompozicije mora biti 0..1 ili 1..1", "r:95ae1a9f-1c78-45b3-9bb4-910a7de66c17(ClassDiagramDSLMilosProrocic.typesystem)", "311480510044090851", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Veza$F6;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty TipVeze$Sa5H = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf5487ef93L, "TipVeze");
    /*package*/ static final SProperty gornjaVrednost$nLo4 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f605L, "gornjaVrednost");
    /*package*/ static final SProperty donjaVrednost$nL93 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f604L, "donjaVrednost");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink kardinalnostLevo$UmOH = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf5488c68cL, "kardinalnostLevo");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Veza$F6 = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, "ClassDiagramDSLMilosProrocic.structure.Veza");
  }
}
