package ClassDiagramDSLMilosProrocic.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Atribut;
  private ConceptPresentation props_Dijagram;
  private ConceptPresentation props_Enumeracija;
  private ConceptPresentation props_EnumeracijaValue;
  private ConceptPresentation props_Interface;
  private ConceptPresentation props_Kardinalnost;
  private ConceptPresentation props_Klasa;
  private ConceptPresentation props_TipAtributa;
  private ConceptPresentation props_Veza;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Atribut:
        if (props_Atribut == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Atribut = cpb.create();
        }
        return props_Atribut;
      case LanguageConceptSwitch.Dijagram:
        if (props_Dijagram == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Dijagram = cpb.create();
        }
        return props_Dijagram;
      case LanguageConceptSwitch.Enumeracija:
        if (props_Enumeracija == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Enumeracija = cpb.create();
        }
        return props_Enumeracija;
      case LanguageConceptSwitch.EnumeracijaValue:
        if (props_EnumeracijaValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_EnumeracijaValue = cpb.create();
        }
        return props_EnumeracijaValue;
      case LanguageConceptSwitch.Interface:
        if (props_Interface == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Interface = cpb.create();
        }
        return props_Interface;
      case LanguageConceptSwitch.Kardinalnost:
        if (props_Kardinalnost == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Kardinalnost");
          props_Kardinalnost = cpb.create();
        }
        return props_Kardinalnost;
      case LanguageConceptSwitch.Klasa:
        if (props_Klasa == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Klasa = cpb.create();
        }
        return props_Klasa;
      case LanguageConceptSwitch.TipAtributa:
        if (props_TipAtributa == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TipAtributa = cpb.create();
        }
        return props_TipAtributa;
      case LanguageConceptSwitch.Veza:
        if (props_Veza == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Veza");
          props_Veza = cpb.create();
        }
        return props_Veza;
    }
    return null;
  }
}
