package ClassDiagramDSLMilosProrocic.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_tipVezeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_tipVezeEnum() {
    super(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e43eL, "tipVezeEnum", "r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231321662");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_agregacija_0 = new EnumerationDescriptor.MemberDescriptor("agregacija", "<>---", 0x505e9faf5487e43fL, "r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231321663");
  private final EnumerationDescriptor.MemberDescriptor myMember_kompozicija_0 = new EnumerationDescriptor.MemberDescriptor("kompozicija", "++---", 0x505e9faf5487e447L, "r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231321671");
  private final EnumerationDescriptor.MemberDescriptor myMember_asocijacija_0 = new EnumerationDescriptor.MemberDescriptor("asocijacija", "-----", 0x505e9faf5487e442L, "r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231321666");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e43eL, 0x505e9faf5487e43fL, 0x505e9faf5487e447L, 0x505e9faf5487e442L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_agregacija_0, myMember_kompozicija_0, myMember_asocijacija_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "agregacija":
        return myMember_agregacija_0;
      case "kompozicija":
        return myMember_kompozicija_0;
      case "asocijacija":
        return myMember_asocijacija_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
