package ClassDiagramDSLMilosProrocic.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Atribut = 0;
  public static final int Dijagram = 1;
  public static final int Enumeracija = 2;
  public static final int EnumeracijaValue = 3;
  public static final int Interface = 4;
  public static final int Kardinalnost = 5;
  public static final int Klasa = 6;
  public static final int Veza = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1930d0ecd9194e4cL, 0xb5d876474568c949L);
    builder.put(0xe5066ba6565f7d1L, Atribut);
    builder.put(0x505e9faf5487e996L, Dijagram);
    builder.put(0xe5066ba6565fc9aL, Enumeracija);
    builder.put(0x505e9faf54891bbdL, EnumeracijaValue);
    builder.put(0xe5066ba65655f5cL, Interface);
    builder.put(0x505e9faf5487ef8eL, Kardinalnost);
    builder.put(0xe5066ba656622fdL, Klasa);
    builder.put(0xe5066ba656622ffL, Veza);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
