package ClassDiagramDSLMilosProrocic.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAtribut = createDescriptorForAtribut();
  /*package*/ final ConceptDescriptor myConceptDijagram = createDescriptorForDijagram();
  /*package*/ final ConceptDescriptor myConceptEnumeracija = createDescriptorForEnumeracija();
  /*package*/ final ConceptDescriptor myConceptEnumeracijaValue = createDescriptorForEnumeracijaValue();
  /*package*/ final ConceptDescriptor myConceptInterface = createDescriptorForInterface();
  /*package*/ final ConceptDescriptor myConceptKardinalnost = createDescriptorForKardinalnost();
  /*package*/ final ConceptDescriptor myConceptKlasa = createDescriptorForKlasa();
  /*package*/ final ConceptDescriptor myConceptTipAtributa = createDescriptorForTipAtributa();
  /*package*/ final ConceptDescriptor myConceptVeza = createDescriptorForVeza();
  /*package*/ final EnumerationDescriptor myEnumerationtipVezeEnum = new EnumerationDescriptor_tipVezeEnum();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAtribut, myConceptDijagram, myConceptEnumeracija, myConceptEnumeracijaValue, myConceptInterface, myConceptKardinalnost, myConceptKlasa, myConceptTipAtributa, myConceptVeza);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Atribut:
        return myConceptAtribut;
      case LanguageConceptSwitch.Dijagram:
        return myConceptDijagram;
      case LanguageConceptSwitch.Enumeracija:
        return myConceptEnumeracija;
      case LanguageConceptSwitch.EnumeracijaValue:
        return myConceptEnumeracijaValue;
      case LanguageConceptSwitch.Interface:
        return myConceptInterface;
      case LanguageConceptSwitch.Kardinalnost:
        return myConceptKardinalnost;
      case LanguageConceptSwitch.Klasa:
        return myConceptKlasa;
      case LanguageConceptSwitch.TipAtributa:
        return myConceptTipAtributa;
      case LanguageConceptSwitch.Veza:
        return myConceptVeza;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationtipVezeEnum);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAtribut() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Atribut", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565f7d1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/1031437265418975185");
    b.version(3);
    b.associate("tipAtributaRef", 0x505e9faf548978a1L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5489789fL).optional(false).origin("5791241746231425185").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDijagram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Dijagram", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231323030");
    b.version(3);
    b.aggregate("klase", 0x505e9faf5487e998L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622fdL).optional(true).ordered(true).multiple(true).origin("5791241746231323032").done();
    b.aggregate("intefejsi", 0x505e9faf5487e999L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba65655f5cL).optional(true).ordered(true).multiple(true).origin("5791241746231323033").done();
    b.aggregate("veze", 0x505e9faf5487e99aL).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL).optional(true).ordered(true).multiple(true).origin("5791241746231323034").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnumeracija() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Enumeracija", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565fc9aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/1031437265418976410");
    b.version(3);
    b.aggregate("vrednosti", 0x505e9faf54891bc7L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf54891bbdL).optional(true).ordered(true).multiple(true).origin("5791241746231401415").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnumeracijaValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "EnumeracijaValue", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf54891bbdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231401405");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInterface() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Interface", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba65655f5cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/1031437265418936156");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKardinalnost() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Kardinalnost", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL);
    b.class_(false, false, false);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231324558");
    b.version(3);
    b.property("donjaVrednost", 0x505e9faf5487f604L).type(PrimitiveTypeId.INTEGER).origin("5791241746231326212").done();
    b.property("gornjaVrednost", 0x505e9faf5487f605L).type(PrimitiveTypeId.STRING).origin("5791241746231326213").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKlasa() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Klasa", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622fdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/1031437265418986237");
    b.version(3);
    b.associate("extendsClass", 0x505e9faf548bc8a5L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622fdL).optional(true).origin("5791241746231576741").done();
    b.aggregate("atributi", 0x505e9faf5487e43bL).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565f7d1L).optional(true).ordered(true).multiple(true).origin("5791241746231321659").done();
    b.aggregate("implementsInterface", 0x505e9faf548bc8a8L).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba65655f5cL).optional(true).ordered(true).multiple(true).origin("5791241746231576744").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTipAtributa() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "TipAtributa", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5489789fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/5791241746231425183");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVeza() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ClassDiagramDSLMilosProrocic", "Veza", 0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL);
    b.class_(false, false, false);
    b.origin("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)/1031437265418986239");
    b.version(3);
    b.property("tipVeze", 0x505e9faf5487ef93L).type(MetaIdFactory.dataTypeId(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e43eL)).origin("5791241746231324563").done();
    b.aggregate("kardinalnostLevo", 0x505e9faf5488c68cL).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL).optional(false).ordered(true).multiple(false).origin("5791241746231379596").done();
    b.aggregate("kardinalnostDesno", 0x505e9faf5488c68dL).target(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL).optional(false).ordered(true).multiple(false).origin("5791241746231379597").done();
    return b.create();
  }
}
