package ClassDiagramDSLMilosProrocic.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "ClassDiagramDSLMilosProrocic";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "Atribut":
          return Collections.<NodeFactory>singletonList(new node_factory_Atribut_name.NodeFactory_4299378402591779224());
        case "Enumeracija":
          return Collections.<NodeFactory>singletonList(new node_factory_Enumeracija_name.NodeFactory_2465447832825166297());
        case "Interface":
          return Collections.<NodeFactory>singletonList(new node_factory_Interface_name.NodeFactory_2465447832824801000());
        case "Klasa":
          return Collections.<NodeFactory>singletonList(new node_factory_Klasa_name.NodeFactory_2465447832825004792());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
