package ClassDiagramDSLMilosProrocic.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public final class Dijagram__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, "ClassDiagramDSLMilosProrocic.structure.Dijagram");

  public static final SMethod<String> getInterfaceSuffix_id3IEtu39uWxB = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getInterfaceSuffix").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4299378402592016487L).languageId(0xb5d876474568c949L, 0x1930d0ecd9194e4cL).build2();
  public static final SMethod<String> getEnumSuffix_id3IEtu39v87s = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getEnumSuffix").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4299378402592063964L).languageId(0xb5d876474568c949L, 0x1930d0ecd9194e4cL).build2();
  public static final SMethod<String> getKlasaSuffix_id3IEtu39vmI3 = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getKlasaSuffix").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4299378402592123779L).languageId(0xb5d876474568c949L, 0x1930d0ecd9194e4cL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getInterfaceSuffix_id3IEtu39uWxB, getEnumSuffix_id3IEtu39v87s, getKlasaSuffix_id3IEtu39vmI3);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getInterfaceSuffix_id3IEtu39uWxB(@NotNull SNode __thisNode__) {
    return " - " + (ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.intefejsi$5e0d)).count() + 1);
  }
  /*package*/ static String getEnumSuffix_id3IEtu39v87s(@NotNull SNode __thisNode__) {
    return " - " + (ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.enumeracije$oHuo)).count() + 1);
  }
  /*package*/ static String getKlasaSuffix_id3IEtu39vmI3(@NotNull SNode __thisNode__) {
    return " - " + (ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.klase$5dLc)).count() + 1);
  }

  /*package*/ Dijagram__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getInterfaceSuffix_id3IEtu39uWxB(node));
      case 1:
        return (T) ((String) getEnumSuffix_id3IEtu39v87s(node));
      case 2:
        return (T) ((String) getKlasaSuffix_id3IEtu39vmI3(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink intefejsi$5e0d = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e999L, "intefejsi");
    /*package*/ static final SContainmentLink enumeracije$oHuo = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5490ab52L, "enumeracije");
    /*package*/ static final SContainmentLink klase$5dLc = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e998L, "klase");
  }
}
