package ClassDiagramDSLMilosProrocic.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ImplementsInterface_SubstituteMenu extends SubstituteMenuBase {
  public ImplementsInterface_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for ImplementsInterface. Generated from implicit smart reference attribute.", new SNodePointer("r:7dadbe6a-db7e-4964-9912-7249092a59c1(ClassDiagramDSLMilosProrocic.structure)", "4049859356191397233")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_ihc6t3_a(), CONCEPTS.ImplementsInterface$Ar));
    result.add(new SMP_Subconcepts_ihc6t3_b());
    return result;
  }

  public class SMP_ReferenceScope_ihc6t3_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_ihc6t3_a() {
      super(CONCEPTS.ImplementsInterface$Ar, LINKS.target$jRFc, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_ihc6t3_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_ihc6t3_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "ImplementsInterface", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.ImplementsInterface$Ar);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ImplementsInterface$Ar = MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x3833fda09c149571L, "ClassDiagramDSLMilosProrocic.structure.ImplementsInterface");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink target$jRFc = MetaAdapterFactory.getReferenceLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x3833fda09c149571L, 0x3833fda09c149573L, "target");
  }
}
