package ClassDiagramDSLMilosProrocic.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class intention_set_Kardinalnost_Veze_1_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public intention_set_Kardinalnost_Veze_1_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:90274395-b22a-4026-877b-f66a97996602(ClassDiagramDSLMilosProrocic.intentions)", "311480510044990914"));
  }

  @Override
  public String getPresentation() {
    return "intention_set_Kardinalnost_Veze_1";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Podesi kardinalnost na 1..1";
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.donjaVrednost$nL93, 1);
      SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4, 1 + "");
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      if (!(isApplicableToNode(node, editorContext))) {
        return false;
      }
      return true;
    }

    private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
      return (SPropertyOperations.getEnum(node, PROPS.TipVeze$Sa5H) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e43eL, "ClassDiagramDSLMilosProrocic.structure.TipVezeEnum"), 0x505e9faf5487e447L, "kompozicija") && ((SPropertyOperations.getInteger(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.donjaVrednost$nL93) > 1 || SPropertyOperations.getInteger(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.donjaVrednost$nL93) < 0) || (!(SPropertyOperations.getString(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4).equals("*")) && Integer.parseInt(SPropertyOperations.getString(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4)) > 1) || (SPropertyOperations.getString(SLinkOperations.getTarget(node, LINKS.kardinalnostLevo$UmOH), PROPS.gornjaVrednost$nLo4).equals("*"))));
    }


    @Override
    public IntentionDescriptor getDescriptor() {
      return intention_set_Kardinalnost_Veze_1_Intention.this;
    }

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink kardinalnostLevo$UmOH = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf5488c68cL, "kardinalnostLevo");
  }

  private static final class PROPS {
    /*package*/ static final SProperty donjaVrednost$nL93 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f604L, "donjaVrednost");
    /*package*/ static final SProperty gornjaVrednost$nLo4 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f605L, "gornjaVrednost");
    /*package*/ static final SProperty TipVeze$Sa5H = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622ffL, 0x505e9faf5487ef93L, "TipVeze");
  }
}
