package ClassDiagramDSLMilosProrocic.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public final class intention_set_Atribut_type_datetime_error_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public intention_set_Atribut_type_datetime_error_Intention() {
    super(Kind.ERROR, false, new SNodePointer("r:90274395-b22a-4026-877b-f66a97996602(ClassDiagramDSLMilosProrocic.intentions)", "1517646760599000008"));
  }

  @Override
  public String getPresentation() {
    return "intention_set_Atribut_type_datetime_error";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Postavi tip datetime";
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SPropertyOperations.assign(node, PROPS.tipAtributa$Len0, "datetime");
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      if (!(isApplicableToNode(node, editorContext))) {
        return false;
      }
      return true;
    }

    private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
      SNode nodeDijagram = (SNode) SNodeOperations.getParent(SNodeOperations.getParent(node));

      for (SNode e : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.enumeracije$oHuo))) {
        if (SPropertyOperations.getString(e, PROPS.name$MnvL) == SPropertyOperations.getString(node, PROPS.tipAtributa$Len0)) {
          return false;
        }
      }

      for (SNode k : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.klase$5dLc))) {
        if (SPropertyOperations.getString(k, PROPS.name$MnvL) == SPropertyOperations.getString(node, PROPS.tipAtributa$Len0)) {
          return false;
        }
      }

      for (SNode i : ListSequence.fromList(SLinkOperations.getChildren(nodeDijagram, LINKS.interfejsi$5e0d))) {
        if (SPropertyOperations.getString(i, PROPS.name$MnvL) == SPropertyOperations.getString(node, PROPS.tipAtributa$Len0)) {
          return false;
        }
      }

      return SPropertyOperations.getString(node, PROPS.tipAtributa$Len0) == null || ("datetime".contains(SPropertyOperations.getString(node, PROPS.tipAtributa$Len0)) && !(SPropertyOperations.getString(node, PROPS.tipAtributa$Len0).equals("date")) && !(SPropertyOperations.getString(node, PROPS.tipAtributa$Len0).equals("datetime")));
    }


    @Override
    public IntentionDescriptor getDescriptor() {
      return intention_set_Atribut_type_datetime_error_Intention.this;
    }

  }

  private static final class PROPS {
    /*package*/ static final SProperty tipAtributa$Len0 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba6565f7d1L, 0x3baa75e0c95b2eb1L, "tipAtributa");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink enumeracije$oHuo = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5490ab52L, "enumeracije");
    /*package*/ static final SContainmentLink klase$5dLc = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e998L, "klase");
    /*package*/ static final SContainmentLink interfejsi$5e0d = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e999L, "interfejsi");
  }
}
