package ClassDiagramDSLMilosProrocic.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class intention_set_Kardinalnost_order_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public intention_set_Kardinalnost_order_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:90274395-b22a-4026-877b-f66a97996602(ClassDiagramDSLMilosProrocic.intentions)", "4299378402590955750"));
  }

  @Override
  public String getPresentation() {
    return "intention_set_Kardinalnost_order";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Postavi ispravan redosled";
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      try {
        if (Integer.parseInt(SPropertyOperations.getString(node, PROPS.gornjaVrednost$nLo4)) < SPropertyOperations.getInteger(node, PROPS.donjaVrednost$nL93)) {
          int pom = SPropertyOperations.getInteger(node, PROPS.donjaVrednost$nL93);
          SPropertyOperations.assign(node, PROPS.donjaVrednost$nL93, Integer.parseInt(SPropertyOperations.getString(node, PROPS.gornjaVrednost$nLo4)));
          SPropertyOperations.assign(node, PROPS.gornjaVrednost$nLo4, pom + "");
        }
      } catch (Exception ex) {
      }
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      return true;
    }



    @Override
    public IntentionDescriptor getDescriptor() {
      return intention_set_Kardinalnost_order_Intention.this;
    }

  }

  private static final class PROPS {
    /*package*/ static final SProperty donjaVrednost$nL93 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f604L, "donjaVrednost");
    /*package*/ static final SProperty gornjaVrednost$nLo4 = MetaAdapterFactory.getProperty(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487ef8eL, 0x505e9faf5487f605L, "gornjaVrednost");
  }
}
