package ClassDiagramDSLMilosProrocic.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public final class intention_add_implementation_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public intention_add_implementation_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:90274395-b22a-4026-877b-f66a97996602(ClassDiagramDSLMilosProrocic.intentions)", "4049859356188818904"));
  }

  @Override
  public String getPresentation() {
    return "intention_add_implementation";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Implementiraj interfejs";
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      try {
        SNode nodeInterface = ListSequence.fromList(SLinkOperations.getChildren(((SNode) SNodeOperations.getParent(node)), LINKS.interfejsi$5e0d)).getElement(0);
        SNode implementsInterface = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x3833fda09c149571L, "ClassDiagramDSLMilosProrocic.structure.ImplementsInterface"));
        SLinkOperations.setTarget(implementsInterface, LINKS.target$jRFc, nodeInterface);
        ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.implementsInterface$DLTP)).addElement(implementsInterface);
      } catch (Exception ex) {
      }
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      return true;
    }



    @Override
    public IntentionDescriptor getDescriptor() {
      return intention_add_implementation_Intention.this;
    }

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink interfejsi$5e0d = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x505e9faf5487e996L, 0x505e9faf5487e999L, "interfejsi");
    /*package*/ static final SReferenceLink target$jRFc = MetaAdapterFactory.getReferenceLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0x3833fda09c149571L, 0x3833fda09c149573L, "target");
    /*package*/ static final SContainmentLink implementsInterface$DLTP = MetaAdapterFactory.getContainmentLink(0x1930d0ecd9194e4cL, 0xb5d876474568c949L, 0xe5066ba656622fdL, 0x505e9faf548bc8a8L, "implementsInterface");
  }
}
